### ISSUE TITLE
Allow using API Tokens

### ISSUE THREAD

**Issue by Enduriel** [fernvenue/cloudflare-ddns#1]
Would be great if it were possible to use an API token rather than the full global key as it is unnecessary.

**Comment by fernvenue** [comment]
Hi @Enduriel, thanks for your suggestion. I do tried to use token instead of global key, but Cloudflare doesn't allow me to update the DNS record like that :(

And yea, if you successfully update your DNS record without global API key, please let me know, and PR welcome :)

I will keep this issue open for now.

**Comment by fernvenue** [comment]
Hi @Enduriel, I just added the support to use API Token instead of Global API Key in https://github.com/fernvenue/cloudflare-ddns/commit/6a40fc488f3b321ddb4b1cb73f0bf672de4f797d :)

**Comment by fernvenue** [comment]
README file updated for it, and I'm gonna close this issue for now, if you have any feedback on this feature, feel free to reopen or submit a new one.
